/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectop;

/**
 *
 * @author Chobo
 */
public class NewJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame3() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(660, 360));
        setResizable(false);
        getContentPane().setLayout(null);

        foto.setBackground(new java.awt.Color(10, 10, 10));
        getContentPane().add(foto);
        foto.setBounds(10, 70, 210, 240);

        jButton1.setText("Cerrar ventana");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 30, 120, 30);

        jComboBox1.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno", "Miguel Hidalgo", "José Morelos" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(120, 30, 150, 20);

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 70, 420, 240);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 30, 220, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/independencia-mexico-660x330.jpg"))); // NOI18N
        jLabel2.setText("JKHJGHFGHjhgj");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        asd = jComboBox1.getSelectedIndex();
        if (asd == 1) {
            jTextPane1.setText("Miguel Gregorio Antonio Ignacio Hidalgo y Costilla Gallaga Mandarte y Villaseñor1 2 (Hacienda de Corralejo en Pénjamo, hoy en el estado de Guanajuato, 8 de mayo de 1753-Chihuahua, Chihuahua, 30 de julio de 1811) fue un sacerdote y revolucionario novohispano que destacó iniciando la primera etapa de la Guerra de Independencia de México con un acto conocido en la historiografía mexicana como Grito de Dolores. Dirigió militar y políticamente la primera parte del movimiento independentista, pero tras una serie de derrotas fue capturado el 21 de marzo de 1811 y llevado prisionero a la ciudad de Chihuahua, donde fue juzgado y fusilado el 30 de julio.");
            jTextField1.setText("Miguel Hidalgo y Costilla");
            foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/miguel hidalgo.gif"))); // NOI18N
            foto.setBounds(10, 40, 470, 320);
        }
        if (asd == 2) {
            jTextPane1.setText("José María Morelos (Valladolid [hoy Morelia], [30 de septiembre] de 1765 - Ecatepec, 22 de diciembre de 1815) ―llamado Siervo de la Nación― fue un sacerdote, militar insurgente y patriota mexicano, que organizó y fue el artífice de la segunda etapa (1811-1815) de la Guerra de Independencia Mexicana, nació en la antigua villa mexicana de Valladolid (hoy llamada Morelia en su honor) y estudió durante los primeros años de su vida con su abuelo materno. Estudió la carrera de sacerdote en el Colegio de San Nicolás y en 1789 entró al seminario de Valladolid, donde se graduó en 1795. En 1799 fue nombrado cura de Carácuaro, donde permaneció hasta 1810.");
            jTextField1.setText("José María Morelos");
            foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Jose_Maria_Morelos-003-Art-Portrait.jpg"))); // NOI18
            foto.setBounds(10, 40, 470, 320);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new NewJFrame3().setVisible(true);

            }

        });

    }
    private int asd;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
